[versions]

kotlin = "1.9.21"
coroutines = "1.7.3"
spigotmc = "1.20.1-R0.1-SNAPSHOT"
logging = "5.1.0"
dokka = "1.8.20"
hoplite = "2.7.5"
koin = "3.5.0"

[libraries]

hoplite-yaml = { module = "com.sksamuel.hoplite:hoplite-yaml", version.ref = "hoplite" }
logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "logging" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
spigotmc = { module = "org.spigotmc:spigot-api", version.ref = "spigotmc" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

# Plugins used in the buildSrc module.
kotlin-jvm-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
