# This workflow builds the modules and publishes them to the Maven central repository.

name: "Continuous Integration"

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
    pull_request:
    release:
      types: [ published ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.pull_request.title, '[ci skip]')
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: --stacktrace --info build
  release:
    name: "Publish"
    runs-on: ubuntu-latest
    needs: build
    if: |
      !contains(github.event.head_commit.message, '[publish skip]') && github.event_name != 'pull_request' &&  github.ref != 'refs/heads/master'
    env:
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: --info build
      - name: Publish with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: -x test publish
